### ISSUE TITLE
css布局规范

### ISSUE THREAD

**Issue by douzi8** [douzi8/lechebang#25]
1. 左 中 右
```css
.left {
  float: left;
}

.right {
  float: right;
}

.center {
  over: hidden;
}
```
```html
<div class="clearfix">
   <!-- 可缺省 -->
   <div class="left"></div>
   <!-- 可缺省 -->
   <div class="right"></div>
   <!-- 自适应宽度 -->
   <div class="center"></div>
</div>
```
```
A: left
B: right
C: center

---------------------
|  A  |    C    |  B  |
---------------------

---------------------
|  A  |     C     |
---------------------

---------------------
|       C       |  B  |
---------------------

```
